type Text = {
	headerTitle: string;
	headerDescription: string;
	aboutTitle: string;
	aboutDescription: string;
	aboutMarkdown: string;
	techTitle: string;
	techDescription: string;
	journeyTitle: string;
	journeyDescription: string;
	journeyNow: string;
	letsTalkTitle: string;
	letsTalkDescription: string;
	socialInstagram: string;
	socialTwitter: string;
	socialEmail: string;
	formName: string;
	formNameError: string;
	formNamePlaceholder: string;
	formEmail: string;
	formEmailError: string;
	formEmailInvalid: string;
	formEmailPlaceholder: string;
	formMessage: string;
	formMessageError: string;
	formMessagePlaceholder: string;
	formCancel: string;
	formSubmit: string;
	formSubmitSuccess: string;
	formSubmitFailed: string;
	footerResume: string;
	footerCopyright: string;
};

export default Text;
